### ISSUE TITLE
addCompositionKernelParameter method is missing a version without a thread modifier

### ISSUE THREAD

**Issue by rtrembecky** [HiPerCoRe/KTT#21]
As of [KTT documentation](https://fillo7.github.io/KTT/classktt_1_1_tuner.html#ad26658449104e00592fb9dc19c804505), `addCompositionKernelParameter` method has only one signature, where `addParameter` has two.

```c++
addCompositionKernelParameter ( const KernelId compositionId, const KernelId kernelId, const std::string & parameterName, const std::vector< size_t > & parameterValues, const ModifierType modifierType, const ModifierAction modifierAction, const ModifierDimension modifierDimension );
addParameter ( const KernelId id, const std::string & parameterName, const std::vector< size_t > & parameterValues );
addParameter ( const KernelId id, const std::string & parameterName, const std::vector< size_t > & parameterValues, const ModifierType modifierType, const ModifierAction modifierAction, const ModifierDimension modifierDimension );
```

I am using `ModifierType::None`, but it is not a nice solution, as the other two arguments are useless.

**Comment by Fillo7** [comment]
You can use regular addParameter() methods for kernel compositions as well (in this case they will affect all kernels inside composition).

The reason why there is no separate addCompositionParameter() method without modifiers is, that it would have the same behaviour as regular addParameter() method (if parameter is not a modifier, then it only affects kernel code, where it can be ignored by specific kernels).

**Comment by rtrembecky** [comment]
I wanted to create another issue on that topic as well, that I can access the parameters from other kernels in composition.

**Comment by rtrembecky** [comment]
So the reason why this `addCompositionParameter` method exists is not to specify a parameter that works only for specific kernel and can't be seen by others, but rather to have means to modify the grid size of this specific kernel and not affect all the kernels in composition. Right? Feel free to close this then.
